### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by Bastes** [justinmimbs/elm-date-extra#10]
Hi :) I've been using this lib and am trying to upgrade my project to elm 0.19 ; apparently it's still on 0.18 ; are there any hangups? May I help?

**Comment by justinmimbs** [comment]
Hi Michel,

Thanks for offering to help. Part of this library was adapted to 0.19 as [time-extra](https://package.elm-lang.org/packages/justinmimbs/time-extra/latest/), and there are other 0.19 libraries that fill in most of the rest. For more info, see [these comments in the README](https://github.com/justinmimbs/elm-date-extra#upgrading-to-elm-019).

Please let me know if there's anything you're missing making the upgrade.

Thanks,

Justin

**Comment by Bastes** [comment]
Thanks for the tips, I'll be looking into all this :)
