### ISSUE TITLE
`infixl 1 >>=` makes library incompatible with other libraries which use this

### ISSUE THREAD

**Issue by panthus** [justinmimbs/elm-date-extra#2]
Due to issue  https://github.com/elm-lang/elm-compiler/issues/1096 in the elm compiler the line `infixl 1 >>=` can only exist once in a project, including its libraries. 

For example this library is now incompatible with https://github.com/Bogdanp/elm-combine and https://github.com/Fresheyeball/elm-return.

Related issues in these libraries:
- https://github.com/Bogdanp/elm-combine/issues/19
- https://github.com/Fresheyeball/elm-return/issues/6

**Comment by justinmimbs** [comment]
Thanks for letting me know! I wasn't aware of this issue. I'll remove it to allow compatibility.
