### ISSUE TITLE
toString function for Interval

### ISSUE THREAD

**Issue by abingham** [justinmimbs/elm-date-extra#3]
I've found that I need a function to get string versions of the `Interval` constructors. Would you be interested in adding that to this library? I could put a PR together if so.

**Comment by justinmimbs** [comment]
Hi there! Are you looking to convert `Interval` constructors to strings? If so, the `toString` function in core will do it (e.g. https://ellie-app.com/3mc9LW7GrFKa1/0). Or are you looking to convert strings to `Interval`s?

**Comment by abingham** [comment]
Huh...I swear I tried that. Thanks for clearing up my brainfart!
