### ISSUE TITLE
unexpected result from diffing 2 dates

### ISSUE THREAD

**Issue by roovo** [justinmimbs/elm-date-extra#4]
Am I going mad here??

```elm
module Main exposing (..)

import Html exposing (Html, text)
import Date exposing (Date, Month(..))
import Date.Extra as DE exposing (Interval(..))

main : Html a
main =
    text ("the same? " ++ (toString (diff1 == diff2)))

diff1 =
    DE.diff Day
        (DE.fromCalendarDate 2022 Mar 27)
        (DE.fromCalendarDate 2022 Apr 3)
        
diff2 =
    DE.diff Day
        (DE.fromCalendarDate 2022 Mar 28)
        (DE.fromCalendarDate 2022 Apr 4)
```

tells me the diffs are not the same - they should both be 7 days, but diff1 is 6....

I feel hesitant to press submit as I must be doing something stupid, but I can't see what!  Please help my sanity recover ;)

**Comment by justinmimbs** [comment]
You're not going mad. :) It's likely you have a DST switch on 27 Mar 2022 where you are, making that day only 23 hours long.

`fromCalendarDate` assumes the values you give it to be in your local time, and `diff Day` returns the difference in terms of 24-hour periods. In other words, `fromCalendarDate` returns a time relative to your current location, but `diff Day` considers the time in more absolute terms (i.e. UTC time). (Perhaps it would be less surprising if `diff Day` worked on the local representation of dates instead. Either way it ends up being ambiguous, as JS Date values are implicitly attached to your local time zone.)

As a workaround, you could shift your local dates to their UTC equivalent before diffing them, like this:
https://ellie-app.com/3Tskq5zTLyna1/0

Does that give the results you expect?

**Comment by roovo** [comment]
brill - thanks hugely - specially for taking the time to explain and produce an ellie (which has now found its way into my code)

So I'm now all good now with tests-a-passing

Very happy - thanks again - you're a ⭐️

**Comment by justinmimbs** [comment]
You're very welcome! Glad I could help. :thumbsup:
