### ISSUE TITLE
Is it in the plans (or already somehow possible) to use localised versions of all the names

### ISSUE THREAD

**Issue by NeverwinterMoon** [justinmimbs/elm-date-extra#5]
Would it be possible to use localised versions of all the names by providing locale, like "et" or "en", or whatever, and by providing the localisation data to get month, week and other names in different languages?

**Comment by justinmimbs** [comment]
Thanks for the interest. Localization isn't currently planned for this library. But there is another library, [rluiten/elm-date-extra](http://package.elm-lang.org/packages/rluiten/elm-date-extra/latest), that includes localization for Estonian and more that you may want to check out, if you haven't already.

**Comment by NeverwinterMoon** [comment]
Aha! I don't know how I managed to miss it. Sadly, it doesn't support all the locales I need (Estonian is only one of about six I need). But that's something already. Thanks a lot!
